language: node_js

node_js:
  - 0.10
notifications:
  - jrxavier@gmail.com

before_install:
  - npm install -g bower
  - npm install -g grunt-cli
  - npm install -g karma-cli
  - npm install -g protractor
  - bower install

before_script: 
  - grunt
  - cd dist

